### ISSUE TITLE
Queue does not work when microseconds activated in FHEM Logging

### ISSUE THREAD

**Issue by hlathome** [domschl/python-fhem#23]
Hello,

when `attr global mseclog 1` is activated, the queue objects are not processed properly:

`DEBUG:FhemEventQueue:EventQueue: invalid date format in date=2022-11-09 time=09:00:53.653, event 2022-11-09 09:00:53.653 DOIF DOIF_SonneUndSchatten Richtung.SuedOst.brightness: 1930 ignored`

Is there a workaround?
Thx!

**Comment by domschl** [comment]
I've committed a potential bugfix, I do not have a running FHEM installation, so I would be happy about a feedback, if this fixes the issue?

**Comment by hlathome** [comment]
Hello domschl,

I think this was the fastest turnaround I have ever seen. I am new to your python module so I probably have not tested all functionality in a true regression sense, but the first quick run of the code which previously failed seems to work just fine now: 

`{'timestamp': datetime.datetime(2022, 11, 9, 12, 2, 31, 908000), 'devicetype': 'MQTT_GENERIC_BRIDGE', 'device': 'hlathome_remote_mqtt', 'reading': 'outgoing-count', 'value': '93006', 'unit': ''}`

If that's the normal desired outcome, it's fixed, many thanks!
