### ISSUE TITLE
Missing timeout on request

### ISSUE THREAD

**Issue by fhempy** [domschl/python-fhem#9]
Hi,

is there a reason why timeout is not used in following line:
https://github.com/domschl/python-fhem/blob/4faea796df37e15c1a6c774465a6b48694d845bf/fhem/fhem/__init__.py#L261

Unfortunately I have sometimes connections errors and this line causes an infinite wait.

**Comment by domschl** [comment]
There was an issue with different behaviour with Py2 and Py3. I found some [useful information](https://stackoverflow.com/questions/2712524/handling-urllib2s-timeout-python) on this, so with next version, I will retest timeouts.

**Comment by domschl** [comment]
should be fixed in upcoming 0.6.0
